ALTER TABLE documents
ADD FOREIGN KEY(dcm_cst_id) REFERENCES customers(cst_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;


ALTER TABLE orders
ADD FOREIGN KEY(ord_dcm_id) REFERENCES documents(dcm_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;


ALTER TABLE positions
ADD FOREIGN KEY(pst_ord_id) REFERENCES orders(ord_id);
ON UPDATE CASCADE
ON DELETE RESTRICT;
